excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://oeilgauche.github.io
title: oeilgauche
tagline: A log of everyday life
description: My awesome new site
paginate: 5
media: assets
metadata:
  _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "blog"
  
